### ISSUE TITLE
Unions not yet supported?

### ISSUE THREAD

**Issue by acomito** [Escape-Technologies/graphman#44]
Getting an error

```
error: Uncaught (in promise) Error: Kind UNION for type WorkItem is not supported yet. Please open an issue.
```
Is this a known limitation at the moment or maybe I have something configured incorrectly?

**Comment by nohehf** [comment]
No, it's a known limitation, I had no APIs to test it. Could you give more details (endpoint if it's public, expected output, etc ?)

EDIT: 
I believe that the output of a type (A | B) should be treated as:
- an object if either of A or B is an object kind
- a scalar if both A and B are scalars

**Comment by nohehf** [comment]
Update: I'll open a PR for supporting more types ASAP, including #47 (INTERFACE)

**Comment by noraj** [comment]
```
$ deno run https://deno.land/x/graphman@v1.1.3/src/cli.ts http://noraj.test:5013/graphql
Creating the postman collection for http://noraj.test:5013/graphql
✅ Granted net access to "noraj.test:5013".
error: Uncaught (in promise) Error: Kind UNION for type SearchResult is not supported yet. Please open an issue.
    throw new Error(
          ^
    at parseType (https://deno.land/x/graphman@v1.1.3/src/outrospector.ts:79:11)
    at https://deno.land/x/graphman@v1.1.3/src/outrospector.ts:166:20
    at Array.forEach (<anonymous>)
    at parseQueryOrMutationType (https://deno.land/x/graphman@v1.1.3/src/outrospector.ts:160:33)
    at outrospect (https://deno.land/x/graphman@v1.1.3/src/outrospector.ts:188:18)
    at createPostmanCollection (https://deno.land/x/graphman@v1.1.3/src/index.ts:13:25)
    at async https://deno.land/x/graphman@v1.1.3/src/cli.ts:41:20
```

The endpoint is a [DVGA](https://github.com/dolevf/Damn-Vulnerable-GraphQL-Application) instance.
